name: Build Ionic Moodle APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install npm dependencies
        run: npm install

      - name: Install Ionic CLI
        run: npm install -g @ionic/cli

      - name: Build Ionic project
        run: ionic build

      - name: Copy web assets to Android (Capacitor only)
        run: npx cap sync android

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses

      - name: Build APK using Gradle
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: moodle-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
