name: Build Ionic Moodle APK with Cordova

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20.18 (required by moodlemobile@5.0.0)
        uses: actions/setup-node@v4
        with:
          node-version: '20.18'

      - name: Install npm dependencies
        run: npm install

      - name: Uninstall old Ionic CLI and install @ionic/cli globally
        run: |
          npm uninstall -g ionic
          npm install -g @ionic/cli

      - name: Remove Android platform
        run: ionic cordova platform rm android

      - name: Add Android platform
        run: ionic cordova platform add android

      

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install Gradle 8.5
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.5

        
      - name: Build APK in production mode
        run: npm run prod:android

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: moodle-release-apk
          path: platforms/android/app/build/outputs/apk/release/app-release.apk
