name: Ionic Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t ionic-android-builder .

      - name: Run Ionic Build inside Docker
        run: |
          run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            ionic-android-builder /bin/sh -c "./build-android.sh"

      - name: Upload APK and AAB
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: |
            platforms/android/app/build/outputs/apk/release/*.apk
            platforms/android/app/build/outputs/bundle/release/*.aab
